### ISSUE TITLE
how to apply promise in SDK

### ISSUE THREAD

**Issue by vqquoc** [goong-io/goong-sdk#8]
Hi

I need to get them all into an array
But I cant

`var geocodingClient = goongSdk({ accessToken: obj.goong_api_key });
var current_path = [];
geocodingClient.geocodingClient.directions.getDirections({
    origin: lat + ',' + .lng,
    destination: .lat + ',' lng,
    alternatives: true,
    vehicle: 'car'
})
.send()
.then(response => {
    const geocoded_waypoints = response.body.geocoded_waypoints;
    geocoded_waypoints.forEach(function (item, index) {
        geocodingClient.geocodingClient.autocomplete.placeDetail({
            placeid: item.place_id
        })
        .send()
        .then(response => {
            var latlng = new goongjs.LngLat(response.body.result.geometry.lng, response.body.result.geometry.lat);
            current_path.push(latlng);
        });
    });
});`

I think, will need promise.
Is there any option for this function?

Or is. I do ajax manually this way? (with ajax promise)
https://docs.goong.io/rest/place/

Thanks so much!

**Comment by iBinh** [comment]
Does this work?
```javascript
await Promsise.all([
// do stuff here
])```

**Comment by vqquoc** [comment]
Solved!

Thank you so much
